modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "betterlootballs"
version = "${version}"
displayName = "Better Cobblemon Lootballs"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.betterlootballs]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterlootballs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterlootballs]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.betterlootballs]]
modId = "cobblemon"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "betterlootballs.mixins.json"
